import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import ForYouPosts from "@/components/foryouposts/ForYouPosts";
import FollowersPosts from "@/components/followerspost/FollowersPosts";
import { HomeContainer } from "@/styles/Home.styled";
import Navbar from "@/components/navbar/Navbar";
import Search from "@/components/search/Search";
import Trends from "@/components/trends/Trends";
import Tweets from "@/components/foryouposts/posts/Tweets";


//*THIS IS THE HOMEPAGE, IT'S WHAT YOU'RE GOING TO SEE FIRST WHEN YOU LOGIN
//*THIS WAS WHERE NEXT DEFINED ALL THEIR OWN PAGE
export default function Home() {
  const [current, setCurrent] = useState<boolean>(false);
  const [active, setActive] = useState<boolean>(false);

  const handleClick = (param: boolean) => {
    setCurrent(param);
    setActive(!active);
  };



  return (
    <HomeContainer>
      <Head>
        <title>Twitter-clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mainHomePage" >
        <Navbar/>
        <main>
          <div className="homeHeader">
            <div className="homeHeading">
              <h1>Home </h1>
            </div>
            <ul className="postGroup" >
              <a
                className={active ? "linkActive" : "link"}
                onClick={() => handleClick(false)}
              >
                <li> For you </li>
              </a>
              <a
                className={!active ? "linkActive" : "link"}
                onClick={() => handleClick(true)}
              >
                <li> Following </li>
              </a>
            </ul>
          </div>
          <div>
            {current == false && <div>
              <ForYouPosts />
              <Tweets />
            </div>}
            {current == true && <FollowersPosts />}
          </div>
        </main>
        <div className="trendsContainer" >
        <Search />
          <Trends />
          </div>
      </div>
    </HomeContainer>
  );
}
