import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import ForYouPosts from "@/components/foryouposts/ForYouPosts";
import FollowersPosts from "@/components/followerspost/FollowersPosts";
import { HomeContainer } from "@/styles/Home.styled";
import Navbar from "@/components/navbar/Navbar";
import Search from "@/components/search/Search";
import Trends from "@/components/trends/Trends";


//*THIS IS THE HOMEPAGE, IT'S WHAT YOU'RE GOING TO SEE FIRST WHEN YOU LOGIN
//*THIS WAS WHERE NEXT DEFINED ALL THEIR OWN PAGE
export default function Home() {
  const [current, setCurrent] = useState<number>(0);
  const [active, setActive] = useState<boolean>(false);

  const handleClick = (param: number) => {
    setCurrent(param);
    setActive(!active);
  };

  return (
    <HomeContainer>
      <Head>
        <title>Twitter-clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mainHomePage" >
        <Navbar/>
        <main>
          <div className="homeHeader">
            <div className="homeHeading">
              <h1>Home </h1>
            </div>
            <ul className="postGroup" >
              <a
                className={current === 0 ? "linkActive" : "link"}
                onClick={() => handleClick(0)}
              >
                <li> For you </li>
              </a>
              <a
                className={current === 1 ? "linkActive" : "link"}
                onClick={() => handleClick(1)}
              >
                <li> Following </li>
              </a>
            </ul>
          </div>
          <div>
            {current === 0 && <ForYouPosts />}
            {current === 1 && <FollowersPosts />}
          </div>
        </main>
        <div className="trendsContainer" >
        <Search />
          <Trends />
          </div>
      </div>
    </HomeContainer>
  );
}
